services:
  - type: web
    name: criavibe
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2
    envVars:
      - key: DB_HOST
        value: srv2022.hstgr.io
      - key: DB_USER
        value: u276112142_criavibe
      - key: DB_NAME
        value: u276112142_criavibe
      - key: R2_ACCOUNT_ID
        value: a0ffb4ddf665d57e3a7295a45a99cd61
      - key: R2_BUCKET_NAME
        value: criavibe-galeria
      - key: R2_PUBLIC_URL
        value: https://pub-4777309db29c4e17b077dda30d8c5af0.r2.dev
